### ISSUE TITLE
Více týdnů dopředu

### ISSUE THREAD

**Issue by bendiscz** [lonebits/tiptrips#1]
Požadavek na možnost vypisovat jízdy dále v budoucnosti, než jen příští týden.
- vymylset, jak pojmenovávat dalši týdny za "Příští týden"
- přidat button pro návrat na aktuální týden (top-right)

**Comment by hellpf** [comment]
Pak tam pridat TODAY tlacitko pls at se da vratit na aktualni tyden.

**Comment by bendiscz** [comment]
V bete je ted 12 tydnu dopredu + to TODAY tlacitko.
