### ISSUE TITLE
O vikendu zobrazovat uz nasledujici tyden

### ISSUE THREAD

**Issue by Sislik42** [lonebits/tiptrips#7]
Jen napad, mozna spis otazka na hlasovani 😁 Co o vikendu zobraozvat uz cesty na nasledujici tyden?

**Comment by bendiscz** [comment]
Zkousel jsem to a rekl bych, ze to je dobra vec :-) Aplikace si normalne pamatuje tyden, kde jsi... ale pokud nastane jedna z nasledujicich udalosti:
- system appku zabije a nastartuje znovu
- cas se preklopi pres pulnoc

tak se kalendar zmeni na "tento tyden", pokud je po-pa, nebo "pristi tyden", pokud je so-ne.

Spolu s tim jsem opravil jeste jeden bug, ktery se projevoval, kdyz aplikace bezela pres pulnoc z nedele na pondeli.

**Comment by bendiscz** [comment]
Je to pripraveno pro release 1.1.0.
